on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        node: ['12', '14', '16']
    name: Testing Node ${{ matrix.node }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - run: npm install

      - if: matrix.os == 'ubuntu-latest' && matrix.node == '16'
        run: npm run format:check

      - if: matrix.os == 'ubuntu-latest' && matrix.node == '16'
        run: npm run lint:check

      - run: npm test

      - if: matrix.os == 'ubuntu-latest' && matrix.node == '16'
        run: npm run coverage

      - if: matrix.os == 'ubuntu-latest' && matrix.node == '16'
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ github.token }}
          path-to-lcov: ./coverage.info
